"""remove unique constraint from cart user_id

Revision ID: 951871080da2
Revises: cf0da153830d
Create Date: 2026-05-31 11:49:20.022800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951871080da2'
down_revision: Union[str, Sequence[str], None] = 'cf0da153830d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_user_id_key'), 'cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('cart_user_id_key'), 'cart', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
